version: 2.1
jobs:
  build:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            make setup
            make activate
            make install
            
      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            make activate
            make lint

  buildDockerImage:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DCKUSER
          password: $DCKPWD
          
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
          
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
 
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag=$TAG .
          echo $DCKPWD | docker login -u $DCKUSER --password-stdin
          docker push $DCKUSER/$TAG

workflows:
  default:
    jobs:
      - build
      - buildDockerImage:
          requires: [build]
      #- sendImageToECR
      #    requires: buildDockerImage
      #- startInfra
      #- 
      #    requires: [build-frontend]