version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  
jobs:
  lint:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/app

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - lint-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - lint-

      - run:
          name: install dependencies
          command: |
            make setup
            make activate
            make install
            
      - save_cache:
          paths:
            - ./capstone
          key: lint-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            make activate
            make lint

  buildDockerImagebkp:
    #https://circleci.com/docs/2.0/building-docker-images/
    #docker:
    #  - image: circleci/golang:1.15
    #    auth:
    #      username: $DCKUSER
    #      password: $DCKPWD
    machine: true
    working_directory: ~/app
    
    steps:
      - checkout
      - run:
         name: Install dependencies
         command: |
           sudo apt update
           sudo apt install --assume-yes awscli
     # - setup_remote_docker:
     #      version: 19.03.13
     #      docker_layer_caching: true
 
      # build and push Docker image
      - run: |
          TAG=$DCKUSER/capstone
          docker build --tag=$TAG .
          echo $DCKPWD | docker login -u $DCKUSER --password-stdin
          docker run -d -p 8001:8000 $TAG
          sleep 10
          echo "Running check after docker run"
          check=`curl -s localhost:8001 | grep -c "^Simple Flask"`
          echo "Check result: "$check
          if [ 1 -eq $check ]
          then 
            echo "Check passed pushing image to dockerhub"
            # get AWS login
            #aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 312139106895.dkr.ecr.us-east-1.amazonaws.com
            docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 312139106895.dkr.ecr.us-east-1.amazonaws.com
            echo "Tagging image for ECR"
          fi

  buildDockerImage:
    machine: true
    working_directory: ~/app
    
    steps:
      - checkout
      - run:
          name: Setup common environment variables
          command: |
            echo 'export TAG=${DCKUSER}/capstone' >> $BASH_ENV
      - run:
          name: Build Image
          command: |
            docker build --tag=$TAG .
            echo $DCKPWD | docker login -u $DCKUSER --password-stdin
            docker run -d -p 8001:8000 $TAG
            sleep 10
            echo "Running check after docker run"
            check=`curl -s localhost:8001 | grep -c "^Simple Flask"`
            echo "Check result: "$check
            if [ 1 -ne $check ]; then echo "Post check build failed";exit 1;fi
      - run:
          name: Save image to an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar $TAG
      - persist_to_workspace:
          root: .
          paths:
            - docker-image

  pushDockerImageToECR:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/app
    
    steps:
      - checkout
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
      - attach_workspace:
          at: ./
      - run:
          name: install dependencies
          command: |
            make setup
            make activate
            pip install awscli
            
      - run:
          name: Push image to ECR
          command: |
            make activate
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$CIRCLE_SHA1
    
workflows:
  default:
    jobs:
      - lint
      - buildDockerImage:
          requires: [lint]
      - pushDockerImageToECR:
          requires: [buildDockerImage]
      #- startInfra
      #- 
      #    requires: [build-frontend]