apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmalloncapstone
  labels:
    app: pmalloncapstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pmalloncapstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pmalloncapstone
    spec:
      containers:
      - name: pmalloncapstone
        image: DOCKER_IMAGE_NAME
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VERSION_INFO
          value: "VERSION_INFO_VAL"
        - name: BUILD_DATE
          value: "BUILD_DATE_VAL"
        ports:
        - containerPort: 8000