apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmalloncapstone
  namespace: default
  labels:
    app: pmalloncapstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pmalloncapstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pmalloncapstone
    spec:
      containers:
      - name: app
        image: DOCKER_IMAGE_NAME
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VERSION_INFO_VAL
          value: "VERSION_INFO"
        - name: BUILD_DATE_VAL
          value: "BUILD_DATE"
        ports:
        - containerPort: 8000